[seaweedfs_nodes]
swfs-n1 ansible_host=10.5.93.212 seaweedfs_rack=rack1 seaweedfs_data_center=dc1
swfs-n2 ansible_host=10.5.93.213 seaweedfs_rack=rack2 seaweedfs_data_center=dc1
swfs-n3 ansible_host=10.5.93.214 seaweedfs_rack=rack3 seaweedfs_data_center=dc1
swfs-n4 ansible_host=10.5.93.215 seaweedfs_rack=rack4 seaweedfs_data_center=dc1

[masters]
swfs-n1
swfs-n2
swfs-n3

[volumes]
swfs-n1
swfs-n2
swfs-n3
swfs-n4

[filers]
swfs-n2
swfs-n3

[s3]
swfs-n2
swfs-n3

[haproxy]
swfs-n1

[all:vars]
ansible_user=root
ansible_become=true
ansible_python_interpreter=/usr/bin/python3
